name: Unit Test
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ develop ] }

jobs:
  unit-tests:
    uses: SJJC-Team/ci/.github/workflows/run-unit-tests.yml@develop
    with:
      ios_scheme_name: whooshing.toolbox-file-storage
      work_dir: "."

      with_release_mode_testing: true
      with_musl: false
      with_api_check: false
      with_coverage: false
      ios_xcodebuild_action: ''

      only_build: false
      with_pg_test: true
      with_pg_database: "postgres"
      with_pg_user: "postgres"
      with_pg_password: "password"
      with_pg_port: "5432"
    secrets: inherit
